---
title: "Initial Data Inspection"
author: "Yunfei Yu, 1005976918"
date: "2026-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, message=FALSE}
library(readxl)
library(dplyr)
library(tidyverse)
library(kableExtra)
library(knitr)
library(skimr)
```

```{r import helper functions}
source("helper_functions.R")
```


# 1 Data checks

## 1.1 Load data and initial inspection

```{r load data}
raw.data <- read_excel("Data/FINAL_ProjectOATH_DATA_2024-05-08_1639.xlsx")
# raw.data %>% skim()
```


# 2 Organizational Ambidexterity Survey Scales



## 2.1 Exploration

### 2.1.1 Check missings and completion rate

```{r exploration scale missing}
# check missingness in exploration scale items
get_missing_stats(data = raw.data, prefix = "explore", caption = "Exploration scale completion rate")
```


## 2.2 Exploitation

```{r exploitation scale missing}
# check missingness in exploitation scale items
get_missing_stats(data = raw.data, prefix = "exploit", caption = "Exploitation scale completion rate")
```

